# Generated by Django 5.1.2 on 2024-10-10 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='astronomyshow',
            name='show_theme',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='astronomy_shows', to='planetarium.showtheme'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
    ]
