# Generated by Django 5.1.2 on 2024-10-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0003_astronomyshow_show_theme_alter_reservation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='astronomyshow',
            name='show_theme',
        ),
        migrations.AddField(
            model_name='astronomyshow',
            name='show_theme',
            field=models.ManyToManyField(related_name='astronomy_shows', to='planetarium.showtheme'),
        ),
    ]
